version: '3.3'
services:

  eureka-peer1:
    hostname: eureka-peer1
    image: ${EUREKA_IMAGE_NAME}
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8761:8761"
    environment:
      - JAVA_OPTS=-Dspring.profiles.active=peer1

  eureka-peer2:
    hostname: eureka-peer2
    image: ${EUREKA_IMAGE_NAME}
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8762:8762"
    environment:
      - JAVA_OPTS=-Dspring.profiles.active=peer2

networks:
  default:
    external:
      name: ${ENV_NAME}
